# Generated by Django 5.1.7 on 2025-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_alter_delivery_person_assigned"),
        ("warehouses", "0014_alter_warehouse_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="destination_warehouses",
            field=models.ManyToManyField(
                related_name="deliveries", to="warehouses.warehouse"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="estimated_time_arrival",
            field=models.DateTimeField(verbose_name="ETA"),
        ),
    ]
