# Generated by Django 5.1.7 on 2025-04-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_delivery_destination_warehouses_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="delivery_address",
            new_name="delivery_notes",
        ),
    ]
