# Generated by Django 5.1.7 on 2025-04-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_alter_delivery_date_delivered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="date_delivered",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivery_notes",
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
    ]
