# Generated by Django 5.1.7 on 2025-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profileuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
