# Generated by Django 5.1.7 on 2025-04-05 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profileuser_name"),
        ("warehouses", "0006_alter_warehouse_warehouse_geotag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="warehouse_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouses.warehouse",
            ),
        ),
    ]
