# Generated by Django 5.1.7 on 2025-04-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profileuser_warehouse_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileuser",
            old_name="warehouse_location",
            new_name="warehouse",
        ),
    ]
