# Generated by Django 5.1.7 on 2025-04-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profileuser_actor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileuser",
            name="email",
        ),
    ]
