# Generated by Django 5.1.7 on 2025-03-30 06:18

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0002_warehouse_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="id",
            field=models.CharField(
                default=core.utils.generate_id,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
