# Generated by Django 5.1.7 on 2025-03-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0003_alter_warehouse_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warehouse",
            old_name="address",
            new_name="warehouse_address",
        ),
        migrations.RenameField(
            model_name="warehouse",
            old_name="geotag",
            new_name="warehouse_geotag",
        ),
        migrations.RenameField(
            model_name="warehouse",
            old_name="name",
            new_name="warehouse_name",
        ),
    ]
