# Generated by Django 5.1.7 on 2025-04-01 10:22

from django.db import migrations, models

import apps.warehouses.utils


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0004_rename_address_warehouse_warehouse_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="warehouse_geotag",
            field=models.CharField(
                max_length=100, validators=[apps.warehouses.utils.validate_geotag]
            ),
        ),
    ]
