# Generated by Django 5.1.7 on 2025-04-01 10:27

from django.db import migrations, models

import apps.warehouses.utils


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0005_alter_warehouse_warehouse_geotag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="warehouse_geotag",
            field=models.CharField(
                max_length=40, validators=[apps.warehouses.utils.validate_geotag]
            ),
        ),
    ]
