# Generated by Django 5.1.7 on 2025-04-05 09:45

from django.db import migrations, models

import apps.warehouses.utils


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0006_alter_warehouse_warehouse_geotag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="id",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="Warehouse Code",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="warehouse_geotag",
            field=models.CharField(
                help_text="Format: 'latitude, longitude'",
                max_length=40,
                validators=[apps.warehouses.utils.validate_geotag],
            ),
        ),
    ]
