# Generated by Django 5.1.7 on 2025-04-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0007_alter_warehouse_id_alter_warehouse_warehouse_geotag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="warehouse_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
