# Generated by Django 5.1.7 on 2025-04-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0010_alter_warehouse_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="warehouse_name",
            field=models.CharField(max_length=255),
        ),
    ]
