# Generated by Django 5.1.7 on 2025-04-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0011_alter_warehouse_warehouse_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
