# Generated by Django 5.1.7 on 2025-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0013_alter_warehouse_code_alter_warehouse_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
