# Generated by Django 5.1.7 on 2025-04-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0014_alter_warehouse_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warehouse",
            old_name="warehouse_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="warehouse",
            old_name="warehouse_geotag",
            new_name="geotag",
        ),
        migrations.RenameField(
            model_name="warehouse",
            old_name="warehouse_name",
            new_name="name",
        ),
    ]
